# Generated by Django 3.0.3 on 2021-03-18 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_imgage',
            field=models.CharField(default='https://www.google.com/url?sa=i&url=https%3A%2F%2Fdribbble.com%2Fwhomohit&psig=AOvVaw1rwLBMZeMU-GGi8oYJLfMW&ust=1616177726881000&source=images&cd=vfe&ved=0CAIQjRxqFwoTCJifjbi5uu8CFQAAAAAdAAAAABAJ', max_length=500),
        ),
    ]
