# Generated by Django 3.0.3 on 2021-03-18 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_item_item_imgage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='item_imgage',
            new_name='item_image',
        ),
    ]
